name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/frame-1.png
    - assets/page-1/images/battery.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/group-2.png
    - assets/page-1/images/majesticons-edit-pen-2.png
    - assets/page-1/images/wifi.png
    - assets/page-1/images/cellular-connection.png
    - assets/page-1/images/mdi-arrow-down-bold.png
    - assets/page-1/images/wifi-jQo.png
    - assets/page-1/images/group-2-eUT.png
    - assets/page-1/images/battery-251.png
    - assets/page-1/images/frame-1-Yqy.png
    - assets/page-1/images/material-symbols-check-box.png
    - assets/page-1/images/mdi-arrow-down-bold-xxB.png
    - assets/page-1/images/wifi-xKu.png
    - assets/page-1/images/image-1-1ej.png
    - assets/page-1/images/mdi-arrow-down-bold-g3M.png
    - assets/page-1/images/mask-group.png
    - assets/page-1/images/mdi-arrow-down-bold-DGo.png
    - assets/page-1/images/mdi-arrow-down-bold-5Qo.png
    - assets/page-1/images/image-1-qWK.png
    - assets/page-1/images/group-3.png
    - assets/page-1/images/mdi-arrow-down-bold-d63.png
    - assets/page-1/images/image-1-Guh.png
    - assets/page-1/images/frame-1-q2s.png
    - assets/page-1/images/group-2-YRh.png
    - assets/page-1/images/wifi-g9q.png
    - assets/page-1/images/image-1-A4B.png
    - assets/page-1/images/mdi-arrow-down-bold-xqq.png
    - assets/page-1/images/cellular-connection-RYP.png
    - assets/page-1/images/material-symbols-arrow-back.png
    - assets/page-1/images/frame-1-QLB.png
    - assets/page-1/images/mask-group-KYF.png
    - assets/page-1/images/cellular-connection-dxF.png
    - assets/page-1/images/wifi-Tbq.png
    - assets/page-1/images/wifi-zkB.png
    - assets/page-1/images/frame-1-5F9.png
    - assets/page-1/images/image-1-n3V.png
    - assets/page-1/images/group-3-hkf.png
    - assets/page-1/images/image-1-Pas.png
    - assets/page-1/images/group-3-HvT.png
    - assets/page-1/images/image-1-2Gj.png
    - assets/page-1/images/cellular-connection-XUP.png
    - assets/page-1/images/group-3-YJw.png
    - assets/page-1/images/group-3-5UX.png
    - assets/page-1/images/image-1-nNw.png
    - assets/page-1/images/battery-pRR.png
    - assets/page-1/images/mdi-arrow-down-bold-Q9y.png
    - assets/page-1/images/image-1-CV9.png
    - assets/page-1/images/mdi-arrow-down-bold-oQw.png
    - assets/page-1/images/majesticons-edit-pen-2-PE3.png
    - assets/page-1/images/frame-1-6UT.png
    - assets/page-1/images/mdi-arrow-down-bold-ZKR.png
    - assets/page-1/images/image-1-ZMM.png
    - assets/page-1/images/image-1-gAP.png
    - assets/page-1/images/frame-1-DZd.png
    - assets/page-1/images/mask-group-iEP.png
    - assets/page-1/images/image-1-vBM.png
    - assets/page-1/images/mdi-arrow-down-bold-nUT.png
    - assets/page-1/images/image-1-id1.png
    - assets/page-1/images/mingcute-transfer-3-fill.png
    - assets/page-1/images/group-2-gqH.png
    - assets/page-1/images/mdi-arrow-down-bold-ndR.png
    - assets/page-1/images/material-symbols-check-box-WJX.png
    - assets/page-1/images/mingcute-transfer-3-fill-hf9.png
    - assets/page-1/images/group-2-RLF.png
    - assets/page-1/images/group-2-7MV.png
    - assets/page-1/images/group-3-JKV.png
    - assets/page-1/images/mingcute-transfer-3-fill-a27.png
    - assets/page-1/images/battery-zhR.png
    - assets/page-1/images/image-1-uvB.png
    - assets/page-1/images/material-symbols-logout.png
    - assets/page-1/images/frame-1-Fvb.png
    - assets/page-1/images/mdi-arrow-down-bold-Bxf.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/mdi-arrow-down-bold-dfy.png
    - assets/page-1/images/mdi-arrow-down-bold-emy.png
    - assets/page-1/images/image-1-aj5.png
    - assets/page-1/images/mask-group-azF.png
    - assets/page-1/images/cellular-connection-KpP.png
    - assets/page-1/images/frame-1-U3M.png
    - assets/page-1/images/battery-LCb.png
    - assets/page-1/images/battery-vHZ.png
    - assets/page-1/images/mingcute-transfer-3-fill-Sm1.png
    - assets/page-1/images/mdi-arrow-down-bold-bjZ.png
    - assets/page-1/images/mingcute-transfer-3-fill-Ats.png
    - assets/page-1/images/material-symbols-arrow-back-8Gj.png
    - assets/page-1/images/cellular-connection-7xw.png
    - assets/page-1/images/majesticons-edit-pen-2-WvP.png
    - assets/page-1/images/mdi-arrow-down-bold-S4b.png
    - assets/page-1/images/mingcute-transfer-3-fill-4Yj.png
    - assets/page-1/images/mask-group-Lr7.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
